-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 20:29:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dentalsys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dentalsys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dentalsys` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `dentalsys` ;

-- -----------------------------------------------------
-- Table `dentalsys`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(12) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `rol` ENUM('ADMIN', 'RECEPCIONISTA', 'ODONTOLOGO', 'PACIENTE') NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`rut` ASC) VISIBLE,
  UNIQUE INDEX (`correo` ASC) VISIBLE,
  UNIQUE INDEX (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`odontologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`odontologo` (
  `id_usuario` INT NOT NULL,
  `especialidad` VARCHAR(100) NOT NULL,
  `numero_registro_salud` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`numero_registro_salud` ASC) VISIBLE,
  CONSTRAINT `fk_odontologo_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dentalsys`.`usuario` (`id_usuario`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`paciente` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(12) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(150) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `estado` TINYINT NOT NULL DEFAULT TRUE,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_paciente`),
  UNIQUE INDEX (`rut` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dentalsys`.`usuario` (`id_usuario`)
    ON DELETE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`ficha_clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`ficha_clinica` (
  `id_ficha` INT NOT NULL AUTO_INCREMENT,
  `fecha_apertura` DATE NOT NULL,
  `antecedentes_medicos` TEXT NULL DEFAULT NULL,
  `alergias` TEXT NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_ficha`),
  UNIQUE INDEX (`id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_ficha_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `dentalsys`.`paciente` (`id_paciente`)
    ON DELETE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`cita` (
  `id_cita` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `motivo` VARCHAR(255) NULL DEFAULT NULL,
  `estado` ENUM('RESERVADA', 'CONFIRMADA', 'COMPLETADA', 'CANCELADA') NOT NULL DEFAULT 'RESERVADA',
  `id_paciente` INT NOT NULL,
  `id_odontologo` INT NOT NULL,
  PRIMARY KEY (`id_cita`),
  INDEX `fk_cita_paciente` (`id_paciente` ASC) VISIBLE,
  INDEX `fk_cita_odontologo` (`id_odontologo` ASC) VISIBLE,
  CONSTRAINT `fk_cita_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `dentalsys`.`paciente` (`id_paciente`),
  CONSTRAINT `fk_cita_odontologo`
    FOREIGN KEY (`id_odontologo`)
    REFERENCES `dentalsys`.`odontologo` (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`tratamiento` (
  `id_tratamiento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `costo_base` DECIMAL(10,2) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`id_tratamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`atencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`atencion` (
  `id_atencion` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `diagnostico` TEXT NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `indicaciones` TEXT NULL DEFAULT NULL,
  `id_cita` INT NULL DEFAULT NULL,
  `id_ficha` INT NOT NULL,
  `id_odontologo` INT NOT NULL,
  PRIMARY KEY (`id_atencion`),
  UNIQUE INDEX (`id_cita` ASC) VISIBLE,
  INDEX `fk_atencion_ficha` (`id_ficha` ASC) VISIBLE,
  INDEX `fk_atencion_odontologo` (`id_odontologo` ASC) VISIBLE,
  CONSTRAINT `fk_atencion_cita`
    FOREIGN KEY (`id_cita`)
    REFERENCES `dentalsys`.`cita` (`id_cita`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_atencion_ficha`
    FOREIGN KEY (`id_ficha`)
    REFERENCES `dentalsys`.`ficha_clinica` (`id_ficha`),
  CONSTRAINT `fk_atencion_odontologo`
    FOREIGN KEY (`id_odontologo`)
    REFERENCES `dentalsys`.`odontologo` (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`atencion_tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`atencion_tratamiento` (
  `id_atencion` INT NOT NULL,
  `id_tratamiento` INT NOT NULL,
  `cantidad` INT NOT NULL DEFAULT 1,
  `costo_aplicado` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_atencion`, `id_tratamiento`),
  INDEX `fk_atentrat_tratamiento` (`id_tratamiento` ASC) VISIBLE,
  CONSTRAINT `fk_atentrat_atencion`
    FOREIGN KEY (`id_atencion`)
    REFERENCES `dentalsys`.`atencion` (`id_atencion`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_atentrat_tratamiento`
    FOREIGN KEY (`id_tratamiento`)
    REFERENCES `dentalsys`.`tratamiento` (`id_tratamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`pago` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `medio_pago` ENUM('EFECTIVO', 'TARJETA', 'TRANSFERENCIA') NOT NULL,
  `estado` ENUM('PENDIENTE', 'PAGADO', 'ANULADO') NOT NULL DEFAULT 'PENDIENTE',
  `id_paciente` INT NOT NULL,
  `id_atencion` INT NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_pago_paciente` (`id_paciente` ASC) VISIBLE,
  INDEX `fk_pago_atencion` (`id_atencion` ASC) VISIBLE,
  CONSTRAINT `fk_pago_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `dentalsys`.`paciente` (`id_paciente`),
  CONSTRAINT `fk_pago_atencion`
    FOREIGN KEY (`id_atencion`)
    REFERENCES `dentalsys`.`atencion` (`id_atencion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`documento_clinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`documento_clinico` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento` ENUM('RECETA', 'EXAMEN', 'CONSENTIMIENTO') NOT NULL,
  `nombre_archivo` VARCHAR(255) NOT NULL,
  `ruta_storage` VARCHAR(500) NOT NULL,
  `fecha_subida` DATETIME NOT NULL,
  `id_paciente` INT NOT NULL,
  `id_atencion` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_docclinico_paciente` (`id_paciente` ASC) VISIBLE,
  INDEX `fk_docclinico_atencion` (`id_atencion` ASC) VISIBLE,
  CONSTRAINT `fk_docclinico_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `dentalsys`.`paciente` (`id_paciente`),
  CONSTRAINT `fk_docclinico_atencion`
    FOREIGN KEY (`id_atencion`)
    REFERENCES `dentalsys`.`atencion` (`id_atencion`)
    ON DELETE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`presupuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`presupuesto` (
  `id_presupuesto` INT NOT NULL AUTO_INCREMENT,
  `fecha_emision` DATE NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `estado` ENUM('PENDIENTE', 'ACEPTADO', 'RECHAZADO', 'VENCIDO') NOT NULL DEFAULT 'PENDIENTE',
  `monto_total` DECIMAL(10,2) NOT NULL,
  `id_paciente` INT NOT NULL,
  `id_odontologo` INT NOT NULL,
  PRIMARY KEY (`id_presupuesto`),
  INDEX `fk_presupuesto_paciente` (`id_paciente` ASC) VISIBLE,
  INDEX `fk_presupuesto_odontologo` (`id_odontologo` ASC) VISIBLE,
  CONSTRAINT `fk_presupuesto_paciente`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `dentalsys`.`paciente` (`id_paciente`),
  CONSTRAINT `fk_presupuesto_odontologo`
    FOREIGN KEY (`id_odontologo`)
    REFERENCES `dentalsys`.`odontologo` (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dentalsys`.`presupuesto_tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dentalsys`.`presupuesto_tratamiento` (
  `id_presupuesto` INT NOT NULL,
  `id_tratamiento` INT NOT NULL,
  `cantidad` INT NOT NULL DEFAULT 1,
  `costo_aplicado` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_presupuesto`, `id_tratamiento`),
  INDEX `fk_prestrat_tratamiento` (`id_tratamiento` ASC) VISIBLE,
  CONSTRAINT `fk_prestrat_presupuesto`
    FOREIGN KEY (`id_presupuesto`)
    REFERENCES `dentalsys`.`presupuesto` (`id_presupuesto`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_prestrat_tratamiento`
    FOREIGN KEY (`id_tratamiento`)
    REFERENCES `dentalsys`.`tratamiento` (`id_tratamiento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
